export const blogData = {
  featured: [
    {
      id: "F01",
      title: "The Rise of Terminal-Based Interfaces in Modern Web Design",
      excerpt:
        "Exploring how retro terminal aesthetics are making a comeback in contemporary web applications and why developers love them.",
      author: "Sarah Chen",
      date: "2025-02-28",
      readTime: "8 min read",
      category: "FEATURED",
      tags: ["design", "terminal", "retro", "UI/UX"],
      likes: 342,
      comments: 57,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "F02",
      title: "Command Line Productivity Hacks Every Developer Should Know",
      excerpt:
        "Boost your workflow with these essential terminal shortcuts and commands that will save you hours of development time.",
      author: "Marcus Johnson",
      date: "2025-02-25",
      readTime: "12 min read",
      category: "FEATURED",
      tags: ["productivity", "terminal", "commands", "workflow"],
      likes: 289,
      comments: 43,
    },
  ],
  americas: [
    {
      id: "A01",
      title: "Silicon Valley's Terminal Revolution: Back to Basics",
      excerpt:
        "How tech giants are embracing minimalist, terminal-inspired interfaces for their internal tools and why it matters.",
      author: "Jessica Rivera",
      date: "2025-02-27",
      readTime: "6 min read",
      category: "AMERICAS",
      tags: ["silicon valley", "tech trends", "minimalism"],
      likes: 178,
      comments: 32,
    },
    {
      id: "A02",
      title: "The Bloomberg Terminal: A Case Study in Lasting Design",
      excerpt:
        "Examining why the Bloomberg Terminal's design has remained largely unchanged for decades while still commanding a premium price.",
      author: "Robert Chang",
      date: "2025-02-24",
      readTime: "10 min read",
      category: "AMERICAS",
      tags: ["bloomberg", "finance", "design", "case study"],
      likes: 203,
      comments: 28,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "A03",
      title: "Terminal-First Development: The New York Startup Scene",
      excerpt:
        "How NYC startups are building terminal-first applications and changing the way we think about user interfaces.",
      author: "Alicia Washington",
      date: "2025-02-22",
      readTime: "7 min read",
      category: "AMERICAS",
      tags: ["startups", "NYC", "development"],
      likes: 156,
      comments: 19,
    },
    {
      id: "A04",
      title: "The Command Line Renaissance in Financial Trading",
      excerpt:
        "Why high-frequency traders and financial institutions are returning to command-line interfaces for speed and efficiency.",
      author: "Michael Torres",
      date: "2025-02-20",
      readTime: "9 min read",
      category: "AMERICAS",
      tags: ["finance", "trading", "efficiency"],
      likes: 167,
      comments: 24,
    },
  ],
  emea: [
    {
      id: "E01",
      title: "London's FinTech Revolution: Terminal-Based Solutions",
      excerpt:
        "How London's financial technology sector is leveraging terminal interfaces to create powerful tools for traders and analysts.",
      author: "Emma Clarke",
      date: "2025-02-26",
      readTime: "8 min read",
      category: "EMEA",
      tags: ["fintech", "london", "finance"],
      likes: 192,
      comments: 36,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "E02",
      title: "Berlin's Developer Culture and the CLI Renaissance",
      excerpt:
        "Inside Berlin's thriving developer community where command-line interfaces are not just tools but a cultural statement.",
      author: "Hans Mueller",
      date: "2025-02-23",
      readTime: "11 min read",
      category: "EMEA",
      tags: ["berlin", "developer culture", "CLI"],
      likes: 145,
      comments: 27,
    },
    {
      id: "E03",
      title: "Terminal Art: The European Digital Art Movement",
      excerpt:
        "How European digital artists are creating stunning visual art using nothing but ASCII characters and terminal displays.",
      author: "Sophie Dubois",
      date: "2025-02-21",
      readTime: "5 min read",
      category: "EMEA",
      tags: ["art", "ASCII", "digital art"],
      likes: 213,
      comments: 41,
    },
    {
      id: "E04",
      title: "Swiss Banking Systems: The Terminal Interface Advantage",
      excerpt:
        "Why Swiss banks continue to rely on terminal-based interfaces for security, reliability, and performance.",
      author: "Thomas Berger",
      date: "2025-02-19",
      readTime: "9 min read",
      category: "EMEA",
      tags: ["banking", "security", "switzerland"],
      likes: 132,
      comments: 18,
    },
  ],
  asiaPacific: [
    {
      id: "AP01",
      title: "Tokyo's Retro-Tech Movement: Embracing Terminal Aesthetics",
      excerpt:
        "How Japanese developers are combining traditional terminal interfaces with modern functionality to create unique applications.",
      author: "Haruki Tanaka",
      date: "2025-02-25",
      readTime: "7 min read",
      category: "ASIA/PACIFIC",
      tags: ["japan", "retro-tech", "aesthetics"],
      likes: 224,
      comments: 39,
      image: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "AP02",
      title: "Terminal-Based Trading in Shanghai's Financial District",
      excerpt:
        "An inside look at how China's financial professionals are using terminal interfaces for lightning-fast market analysis.",
      author: "Li Wei",
      date: "2025-02-22",
      readTime: "10 min read",
      category: "ASIA/PACIFIC",
      tags: ["china", "trading", "finance"],
      likes: 187,
      comments: 29,
    },
    {
      id: "AP03",
      title: "Sydney's Developer Bootcamps Focus on Command Line Mastery",
      excerpt: "Why Australia's top coding schools are putting terminal skills at the forefront of their curriculum.",
      author: "James Wilson",
      date: "2025-02-20",
      readTime: "6 min read",
      category: "ASIA/PACIFIC",
      tags: ["education", "australia", "coding"],
      likes: 156,
      comments: 22,
    },
  ],
}
